
server:
  port: 5555

spring:
  application:
    name: zuul-server

eureka:
  instance:
    preferIpAddress: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
        - hystrix.stream
        - routes
        - filters

zuul:
  prefix: /api
  routes:
    eureka-client: /gateway/**
    github:
      path: /github/**
      url: https://github.com/hwjoy
