
server:
  port: 8181

spring:
  application:
    name: feign-consumer

eureka:
  instance:
    preferIpAddress: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
